# Generated by Django 4.0.6 on 2022-07-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seller_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.seller'),
            preserve_default=False,
        ),
    ]
