# Generated by Django 4.0.6 on 2022-07-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_event_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
